name: Azure Pages CI
on: [push, pull_request]
jobs:

  azure_pages_job:

    runs-on: ubuntu-latest

    name: Build And Deploy

    steps:

    - uses: actions/checkout@v1
    - shell: bash
      run: |
        zip -r -q /app.zip .
    - shell: bash
      run: |
        ls
